### ISSUE TITLE
TODO - Document all loadouts

### ISSUE THREAD

**Issue by Tapawingo** [clustermod/HCMF3-Loadouts#23]
# Tasks
- [X] Document Australia Loadouts
- [X] Document Congo Loadouts
- [X] Document Fictional Loadouts
- [x] Document Germany Loadouts
- [x] Document Norway Loadouts
- [x] Document Poland Loadouts
- [x] Document Russia Loadouts
- [x] Document Ukraine Loadouts
- [x] Document Unaffiliated Loadouts
- [x] Document United States Loadouts

**Comment by PervonHarke** [comment]
Smh you didn't check all the checkboxes before marking it as complete.

**Comment by Tapawingo** [comment]
> Smh you didn't check all the checkboxes before marking it as complete.

I accidentally auto closed it when I merged the PR
