### ISSUE TITLE
TODO - Add Loadout headers to all loadouts

### ISSUE THREAD

**Issue by Tapawingo** [clustermod/HCMF3-Loadouts#39]
# Tasks
- [X] Add Loadout header to Australia Loadouts
- [X] Add Loadout header to Congo Loadouts
- [X] Add Loadout header to Fictional Loadouts
- [ ] Add Loadout header to Germany Loadouts
- [ ] Add Loadout header to Norway Loadouts
- [ ] Add Loadout header to Poland Loadouts
- [ ] Add Loadout header to Russia Loadouts
- [ ] Add Loadout header to Ukraine Loadouts
- [ ] Add Loadout header to Unaffiliated Loadouts
- [ ] Add Loadout header to United States Loadouts

**Comment by Tapawingo** [comment]
This will be the final TODO task from me in regards to documentation. Once this is completed I believe the repository is well documented and by extension been made much easier for mission-makers to navigate and find loadouts or information about loadouts.
