### ISSUE TITLE
TODO - Update all V4 loadouts to V5

### ISSUE THREAD

**Issue by PervonHarke** [clustermod/HCMF3-Loadouts#41]
With CC Modpack advancing to V5 only one minor mod was added and none removed, therefore all files compatible with V4 are compatible with V5. Only names, headers and documentation need to be changed. 

# Tasks
- [ ] Update v4 compatible Loadouts to v5, Australia
- [ ] Update v4 compatible Loadouts to v5,  Congo
- [ ] Update v4 compatible Loadouts to v5,  Fictional
- [ ] Update v4 compatible Loadouts to v5,  Germany
- [ ] Update v4 compatible Loadouts to v5,  Norway
- [ ] Update v4 compatible Loadouts to v5,  Poland
- [ ] Update v4 compatible Loadouts to v5,  Russia
- [ ] Update v4 compatible Loadouts to v5,  Ukraine
- [ ] Update v4 compatible Loadouts to v5,  Unaffiliated
- [ ] Update v4 compatible Loadouts to v5,  United States
